### PR TITLE
WIP: Flickr date range option

### PR DESCRIPTION
**Pull request by garrettc**
Leaving this as draft for now, it's very much a work in progress but I wanted to get your input.

I couldn't work out a way to make nested mutually exclusive arguments (ie: you must have `date`, **or** `start` **and** `end`), and it doesn't seem it's currently possible in Python, so I switched to using a `range` argument with comma seperated dates: `--range=YYYY-MM-DD,YYYY-MM-DD`.

This is currently immaterial as the `--range` option isn't working correctly, it's downloading a lot more than I'm asking it, even if I give it `--range=2020-03-01,2020-03-01` (a day on which I only took [one photo](https://www.flickr.com/photos/garrettc/49604482963/in/datetaken/)). Not sure if I'm misunderstanding something about the code or the `flickr.photos.search` method. If you can shine any light there it would be welcome.

The other issue is, this feels really hacky. Maybe that's okay, but I get a little twitchy when I'm adding lots of `if` statements everywhere. It's not feeling very elegant. Is there a better way to approach this?

On the plus side, the `--days` option still works.

### CODE REVIEW

**Comment by philgyford** [comment]
Hi, I did get notified, just been busy with work! Will try and look before too long. Thanks for this.

**Comment by philgyford** [comment]
First, congratulations on getting this far and working your way through my labyrinthine layers of classes. I think I have a tendency to go a bit OTT with OOP some times and it can get a bit tricky to work through exactly what's where and how we actually end up at the bit that's going to do the bloody work!

I reckon your initial idea of having separate start and end dates makes sense, rather than a range. That way if, for example, fetching everything failed at a certain point it makes it easier to say "fetch everything older than 2021-01-01" without having to add a start date just because the code requires one.

I think we should stick to fetching by using the _upload_ dates, rather than _taken_ dates. Either could make sense, but I think that in terms of "copying things that exist on another service" it makes more sense to think about when the things appeared on that service (upload), rather than another date on which that thing was actually created elsewhere in the world (taken).

The reason that it's fetching more photos than expected is because in `RecentPhotosFetcher._call_api()` it [first checks to see if `self.min_date` is set](https://github.com/philgyford/django-ditto/blob/712989db37532a7810139dd2f7007c66652a0dd7/ditto/flickr/fetch/fetchers.py#L408). Understandably you've assumed that it's not because you've only set the `min_taken_date` and `max_taken_date`. But you didn't reckon with my possibly unconventional and, certainly, now annoying decision to [set the default `min_date`](https://github.com/philgyford/django-ditto/blob/712989db37532a7810139dd2f7007c66652a0dd7/ditto/flickr/fetch/fetchers.py#L64-L66) to "2000-01-01" (before Flickr existed) so that, if no min date is set, we just fetch everything.

So, in fact, `min_date` was set, and it was never getting to your new API call!

I would _assume_ that we could just not send a min date at all, and it would fetch everything, which makes me wonder why I did that. But it wouldn't be the strangest bit of code I've ever written!

So my suggestions for next steps, if you can still bear it, are:

1. Change the command to use `--start-date` and `--end-date` instead of `--range`, and allow for either or both.
2. Delete the default for `Fetcher.min_date` - it's only used in the `RecentFetcher` class from what I can see, so it seems confusing to have it set like that, and set there.
3. But, maybe set a default for `RecentPhotosFetcher.min_date` and `RecentPhotosFetcher.max_date`, both to `None`.
4. Then in `RecentPhotosFetcher.fetch()`:
    - If `days` is passed in AND (`start_date` OR `end_date`) is passed in, raise a `ValueError`
    - Maybe, to be nice, if `start_date` and `end_date` are passed in, raise a `ValueError` if the former is after the latter?
    - if `days` is passed in, set `min_date` as now.
    - if `start_date` is passed in, set `min_date`
    - if `end_date` is passed in, set `max_date`
5. In `RecentPhotosFetcher._call_api()`, make up the initial arguments in a dict:
    ```python
    api_args = {
        "user_id": self.account.user.nsid,
        "per_page": self.items_per_page,
        "page": self.page_number,
    }
    ```
    and then if `min_date` or `max_date` are set, add those arguments to the dict. Then call the API:
    ```python
    results = self.api.people.getPhotos(**api_args)
    ```

So we're really just using `days` and `min_date` as different ways to define the same `min_date` internally. And adding an optional `max_date` as well.

How does that sound?

**Comment by garrettc** [comment]
So I think I've got the major pieces of that in place, but I'm getting an error that I don't quite understand.

If I run it with `python manage.py fetch_flickr_photos --account=35468140272@N01 --days=3` it's throwing:

```
File "/Users/garrettc/sandbox/polytechnic/env/lib/python3.9/site-packages/ditto/flickr/fetch/fetchers.py", line 108, in _fetch_pages
    while self.page_number <= self.total_pages and self._not_failed():
AttributeError: 'RecentPhotosFetcher' object has no attribute 'page_number'
```

`self.page_number` is being set in `Fetcher`s `__init__` so shouldn't it be picking that up?

**Comment by philgyford** [comment]
Odd - I just had a quick go and I got this error instead:

```
  File "/Users/phil/Projects/personal/django-ditto/ditto/flickr/fetch/multifetchers.py", line 2, in <module>
    from .fetchers import RecentPhotosFetcher, PhotosetsFetcher
  File "/Users/phil/Projects/personal/django-ditto/ditto/flickr/fetch/fetchers.py", line 402
    if start > end:
SyntaxError: expected 'except' or 'finally' block
```

Don't have time right now to look into it further. Maybe this evening.

**Comment by garrettc** [comment]
That's my fault, I forgot to run black so there was an indent problem. You should see the error I'm seeing now. I'll keep hacking away in the meantime and let you know if I get any further.

**Comment by philgyford** [comment]
It's because here:

```python
class RecentPhotosFetcher(PhotosFetcher):

    def __init__(self, account):
        # Minimum date of photos to return
        self.min_date = None

        # Maximum date of photos to return
        self.max_date = None
```

...you need to call `super()._init__(account)` (probably best at the start of the method). As it is you're overriding `Fetch.__init__()` entirely so none of the variables set in there are getting set.

**Comment by garrettc** [comment]
Ah yes, whoops, classes and all that jazz. [_facepalm_]

Okay, I don't want to jinx it, but I think we've got something here. It all appears to be working, and I've added in some tests for the new options. 

Have a look, all feedback welcome.

**Comment by philgyford** [comment]
I think that's good to go!

I just re-jigged the logic very slightly around the arguments and I made it so you don't have to set `start` *and* `end`, but can just do one or the other. And then I fixed the now-broken tests (god those tests are confusing) and added a handful of new ones.

Thanks so much for the idea and the code!

**Comment by philgyford** [comment]
Oops, should merge it *before* closing, doh.

**Pull request merged**
